default: &DEFAULT

  data_format: 'channels_last'
  input_shape: [None, 256, 256, 100]

  learning_rate: 1e-4
  dataset_size: 7000
  batchsize: 16
  epochs: 100
  augment_data: False
  

  # add other default parameters here

  train_data_files: ['/path/to/data/file_0.tfrecords',
                     '/path/to/data/file_1.tfrecords']
  valid_data_files: ['/path/to/data/file_2.tfrecords']

  experiment_dir: 'logs/default_dont_use'

baseline_experiment:
  <<: *DEFAULT
  experiment_dir: 'logs/baseline'

baseline_lr_1e-3:
  <<: *DEFAULT
  learning_rate: 1e-3
  experiment_dir: 'logs/baseline_lr_1e-3'
